### ISSUE TITLE
Implement Github Action

### ISSUE THREAD

**Issue by rndmh3ro** [ansible-community/antsichaut#2]
First working version: https://github.com/rndmh3ro/antsichaut-action/

**Comment by cidrblock** [comment]
Here's an example of a github action that is triggered on a push. Both release drafter and antsichaut are run and a PR is authored for the changelog update https://github.com/ansible-collections/ansible.scm/blob/main/.github/workflows/push.yml

It still needs some cleanup, I'd like to get rid of the need to run pre-commit in the action to format the files but it was necessary so pre-commit didn't need to run and push to the PR

**Comment by rndmh3ro** [comment]
We also have an example here (that's also linked in the readme): https://github.com/T-Systems-MMS/ansible-collection-icinga-director/blob/21e39f00ad792a36be1373c9d8755caa8b2bc2a5/.github/workflows/release.yml


What I thought about with this issue is to create an action that can be used like this:

```
      - name: Run antsichaut
        uses: ansible-community/antsichaut
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINCE_VERSION: "${{ steps.previoustag.outputs.tag }}"
```

This way we don't need to install antsichaut with pip, we have versioning, it's more "official" and so on. However creating an Action is a real PITA so I didn't continue implementing this. Also the current approach is IMO good enough.
